CREATE DATABASE IF NOT EXISTS accredain;

USE accredain;

CREATE TABLE IF NOT EXISTS users (
    id INT PRIMARY KEY  AUTO_INCREMENT,
    name VARCHAR(225) NOT NULL,
    username VARCHAR(255) UNIQUE ,
    email VARCHAR(255) UNIQUE ,
    password VARCHAR(225) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
